name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: ${{ matrix.os }} - Atom ${{ matrix.atom_channel }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        atom_channel: [stable]
    steps:
      - uses: actions/checkout@v2
      - uses: UziTech/action-setup-atom@v1
        with:
          channel: ${{ matrix.atom_channel }}

      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"

      - name: Install dependencies
        run: |
          apm install --production
          npm install --only=dev

      - name: Run tests 👩🏾‍💻
        run: npm run lint

  Lint:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: ${{ matrix.os }} - Atom ${{ matrix.atom_channel }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"

      - name: Install dependencies
        run: npm install

      - name: Run tests 👩🏾‍💻
        run: npm run test.lint
